version: '3.8'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: vayeate
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
